version: '3.8'

services:
  backend:
    build:
      context: ./GlobalDorm
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017/GlobalDorm

  frontend:
    build:
      context: ./global-dorm-frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:3000"
    depends_on:
      - backend
